#!/usr/bin/env bash
# Tool Name :- F-IP-Checker
# Author :- SURJO99exe
# Date :- 03/03/2026

case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.tracefip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: f-ip-checker -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .F-IP-Checker.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    echo "Usage: f-ip-checker [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h                  to show help."
    echo " -u                  to update f-ip-checker."
    echo " help                to show help."
    echo " update              to update f-ip-checker."
    echo " start               to start f-ip-checker menu."
esac
